CCOMP = gcc # C compiler
CFLAGS = -o # Compiler flags
SOURCES = main.c readFiles.c writeFiles.c Checks.c # Sources contained in the project
TARGET = ChristmaList.exe # The generated .exe file

all:
	$(CCOMP) $(SOURCES) $(CFLAGS) $(TARGET)
clean:
	del -fr $(TARGET)